### ISSUE TITLE
Use sys_categories table for facetting

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#121]
Since TYPO3 features a dedicated categories table, this should be used for the facetting feature instead of a proprietary category table.

**Comment by MarkusBausK** [comment]
Are there any news about that topic? This extension is doing something like it is needed: https://extensions.typo3.org/extension/kesearch_categories/ but it's not working correctly in TYPO3 8.7. In my current project it would be really nice to have because there are more than 100 categories in 4 languages :-|

**Comment by christianbltr** [comment]
This feature is now implemented in the master branch and will be in next version after 3.1.6.
