### ISSUE TITLE
Translated Pages not indexed (version 2.5.0)

### ISSUE THREAD

**Issue by ulrike-cosmoblonde** [teaminmedias-pluswerk/ke_search#135]
I updated ke_search from 2.4.2 to 2.5.0 on 3 different TYPO3 projects (TYPO3 7.6. and 8).
After re-indexing, only pages with language ID =0 were in the indexes. Other content (like news) was still indexed in all languages.
After reverting to 2.4.2 the indexing of non-default-language pages was working again.

Is this a known issue?

**Comment by dr-bock** [comment]
Can confirm this bug.

**Comment by Talroon** [comment]
I can also confirm this bug and did some digging in the code:
As far as I can tell the reason is a change in the `$sysLanguages` array of the page indexer.
In the old version `BackendUtility::getSystemLanguages` was used, which returned an array with numbered indexes.
Now `TranslationConfigurationProvider->getSystemLanguages` is used (with an undefined `$pageId` parameter) and that returns an associative array.
https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php#L175

This leads to `if ($sysLang[1] > 0)` never being true: https://github.com/teaminmedias-pluswerk/ke_search/blob/master/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php#L282

I changed `$sysLang[1]` to `$sysLang['uid']` on all three occasions and it seems to be working.
Additionally `GeneralUtility::array_merge` was removed in v8 so I followed the suggestion in v7 and changed it to `$pageOverlay + $pageRow`

**Comment by AndreasA** [comment]
As further information the issue was added when switching from \TYPO3\CMS\Backend\Utility\BackendUtility::getSystemLanguages to the TranslationConfigurationProvider
with the TYPO3 CMS 8 changes here: https://github.com/teaminmedias-pluswerk/ke_search/commit/8409dda2eaa90a3cd5ca7f74f94ac3ec60821a05

The reason is that \TYPO3\CMS\Backend\Utility\BackendUtility::getSystemLanguages did some pre-parsing before returning the languages. 
Of course, it has been removed in 8.7
