### ISSUE TITLE
Call to a member function getExtension() on null

### ISSUE THREAD

**Issue by kristianHH** [teaminmedias-pluswerk/ke_search#158]
In Typo3 8.7 I get when I start the indexer the following error message:

Call to a member function getExtension () on null

The following is the protocol:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getExtension() on null | Error thrown in file /home/typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php in line 657. Requested URL: http://www.xxx.de/typo3/index.php?M=web_KeSearchBackendModule&moduleToken=0e401e98d2bc9d243bf1fc69c33acf7d7f78a2c2&id=14&do=startindexer

What could be the reason?

**Comment by christianbltr** [comment]
ke_search tries to the extension (like "pdf") of a file which should be indexed but fails. Maybe the file as been deleted? Could you check that?

**Comment by kiwi2101** [comment]
I've had the same problem in Typo3 8.7. There was a contentelement with a link to a non-existing file. It might be a Typo3 issue, but shouldn't ke_search check if the $fileObject actually exists before it tries to get $fileObject->getExtension() in file /home/typo3conf/ext/ke_search/Classes/indexer/types/class.tx_kesearch_indexer_types_page.php in line 657? Otherwise the whole indexing process breaks at this point!

**Comment by ulrike-cosmoblonde** [comment]
Hi, got the same problem. Could you please add a check for $fileObject.
Thank you!

**Comment by nemstaa** [comment]
If I'm right:
In class.tx_kesearch_indexer_types_page.php on line 651 in function "indexFiles" a FileInterface-Check is required, which I added manually:
`foreach ($fileObjects as $fileObject) {
    if ($fileObject instanceof FileInterface) {
        $isInList = \TYPO3\CMS\Core\Utility\GeneralUtility::inList(
            $this->indexerConfig['fileext'],
            $fileObject->getExtension()
        );
        /*...*/
    }
}`

or add a validation in function "findLinkedFilesInRte" for Typo3 8.7.x.

Thanks!


Regards
Robert
