### ISSUE TITLE
Indexer for ext:mask

### ISSUE THREAD

**Issue by christianbltr** [teaminmedias-pluswerk/ke_search#277]
As an integrator I want to be able to index content element created with the extension "mask" in order to make the content of those elements to the search results.

*acceptance criteria*
- Mask content elements will get indexed by the page indexer and the content element indexer.
- Content stored in the tt_content table will be indexed and also content stored in tables created by the mask extension.

**Comment by ursbraem** [comment]
ha! My thema! I have a working "mask indexer" if you want to have a look at it. But it's not that good, because you have to enter all fieldnames manually in the indexer config.

**Comment by christianbltr** [comment]
Do you have it publicly available (eg. GitHub)?

**Comment by ursbraem** [comment]
Not really, it's part of a custom extension. But I've made a gist with the files:
https://gist.github.com/ursbraem/098c7b66df4b7784b6662d65aeac112e 

It's TYPO3 7.6, so probably not worth too much. If you want the full extension, I'll prepare it. Ah, and it will receive an upgrade to 9.5 very soon.

In TYPO3, only the "Mask Pages indexer" is set up. It calls the content indexer.
I have to configure the items manually; it should read them from `mask.json`.

<img width="901" alt="Bildschirmfoto 2019-03-12 um 20 53 10" src="https://user-images.githubusercontent.com/1446443/54231653-3227c480-4509-11e9-811e-41248726528c.png">

**Comment by ursbraem** [comment]
I think you will know most of the code 😀

**Comment by cepheiVV** [comment]
To index mask content I would usually just use this hook of ke_search like so:
https://gist.github.com/cepheiVV/1d4fc6ef2eea965693faf7085b371833

This could easily be adapted, in order for Integrators to add their own fields in the backend or in typoscript.
It could also easily be automated, like "Select all `tt_content` fields whicht start with `tx_mask_`".
All tho you can't exclude content that way.

(This might rather be part of EXT:mask instead of EXT:ke_search)

**Comment by christianbltr** [comment]
Since there's now a 3rd party extension to index mask I'm closing this.

Have a look at https://extensions.typo3.org/extension/mask_kesearch_indexer/
