### ISSUE TITLE
Confused about different results

### ISSUE THREAD

**Issue by cosmox** [teaminmedias-pluswerk/ke_search#293]
- DB Server version: 10.1.38-MariaDB-0+deb9u1 Debian 9.8
- TYPO3: 8.7.26
- ke_search: 2.8.1

Hi there,
after our customer ist call us about missing results, i have to take a closer look at the used queries, maybe there are some details that i am not understand, but if i compare the results from MATCH AGAINST with a LIKE query the results are different:
(i test this with a simplified query of the used statement, please correct me if i am wrong)

`
SELECT SQL_CALC_FOUND_ROWS *, MATCH (title) AGAINST ("ODA") FROM tx_kesearch_index WHERE 1=1 AND MATCH (title) AGAINST ('ODA*' IN BOOLEAN MODE) 
`

> = 0 Result

`
SELECT *  FROM `tx_kesearch_index` WHERE `title` LIKE 'ODA%'
`

> = 1 Result

`
SELECT SQL_CALC_FOUND_ROWS *, MATCH (title) AGAINST ("HIS") FROM tx_kesearch_index WHERE 1=1 AND MATCH (title) AGAINST ('HIS*' IN BOOLEAN MODE)
`

> = 33 Results

`
SELECT *  FROM `tx_kesearch_index` WHERE `title` LIKE 'HIS%'
`

> = 75 Results

Is it possible that the current used query not found every matching string or why there is a difference by the used statments?

**Comment by typecat** [comment]
I have a similar strange behavior on 
* TYPO3 9.5.20
* EXT:ke_search 3.1.6
* MySQL 5.7.31

The problem seems to be in the `MATCH` constraint. For instance:
```
SELECT count(*)
 FROM `tx_kesearch_index`
 WHERE MATCH (title,content) AGAINST ('TES*' IN BOOLEAN MODE)
```
returns 2 results. And using
```
SELECT count(*)
 FROM `tx_kesearch_index`
 WHERE title LIKE '%TES%' OR content LIKE '%TES%';
```
returns 250.

I ran into this issue while upgrading a project from
* TYPO3 8.7.24
* EXT:ke_search 2.8.1
* MySQL  5.7.31

There the search for the target string with only 3 characters (and yes, the search word length in both versions is set to 3), works fine and returns the expected 250 results.

In the upgraded system, if I search for the target characters and an additional string (e.g. "TES Hello") more results appear. This is strange, especially if partial word search is enabled as well.

Unfortunately I am not really familiar with `MATCH` constraints. Any ideas what might cause this strange behavior?

**Comment by christianbltr** [comment]
Did you check if "Explicit AND" ist set in the extension configuration? If this option is set, a second word in the search query will be added with an AND conjunction, otherwise with an OR conjuction. Not using "explicit AND" will give you more results.

The partial word search will only find strings at the beginning of words, in words. That's a difference to using "LIKE %...%". See also https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/3.1/en-us/Behaviour/Options.html

**Comment by typecat** [comment]
@christianbltr "Explicit AND" is not enabled in both versions of the project. The partial word search is enabled. In short: the extension configuration is the same, still I get different results on TYPO3 8.7.24 and EXT:ke_search 2.8.1 compared to TYPO3 9.5.20 and EXT:ke_search 3.1.6. That's what confuses me. I didn't change anything except come code style in the fluid templates.

**Comment by ecosmox36** [comment]
today im must confirming this behaviour on another Project

- TYPO3: 10.4.15
- ke_Search: 3.6.1
- DB: '10.2.34-MariaDB-1:10.2.34

Query inside log
(simplified)

```
SELECT *, 
MATCH (title, content) AGAINST ('Ber')+ (1 * MATCH (title) AGAINST ('Ber')) AS score 
FROM `tx_kesearch_index` 
WHERE 1=1 AND MATCH (title,content) AGAINST ('Ber*' IN BOOLEAN MODE)  
```

Result 8
`
SELECT * FROM `tx_kesearch_index` WHERE `content` LIKE '%Ber%' OR `title` LIKE '%Ber%' `

Result 10

Maybe this will help to understand this behaviour:
https://dba.stackexchange.com/questions/21118/why-full-text-search-returns-less-rows-than-like

Im not shure but i guess ke_search uses the LIKE Syntax in earlier versions?

**Comment by christianbltr** [comment]
No, ke_search used MATCH AGAINST also in earlier versions, this gives a score used for the "relevance" ranking. Using LIKE will not give a score.

**Comment by ecosmox36** [comment]
Hi Christian,

thanks for reply,  but why is there a different result between LIKE and MATCH AGAINST, any ideas?

**Comment by christianbltr** [comment]
One difference is: If you use LIKE '%Ber%', you will get results where Ber is in the middle of the word (e. g. "Saubermann").

MATCH AGAINST 'Ber*' will only give you results where "Ber" is at the beginning of the word, like in "Berlin".

Also you will need to configure ke_search to find 3-character-words like described in https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/master/en-us/Configuration/SearchWordLength.html

**Comment by christianbltr** [comment]
ke_search has moved to https://github.com/tpwd/ke_search/, therefore this issue will be closed now.
Please feel free to open another issue at https://github.com/tpwd/ke_search/issues if you feel this issue should still be addressed.
