### ISSUE TITLE
Can't index subheader

### ISSUE THREAD

**Issue by mjpr263** [teaminmedias-pluswerk/ke_search#372]
After setting up an page-indexer for my site most contents are indexed.
I have a few own contentelements (not setted up with mask or anything else but coded as an own extension), this contents where not indexed as well. After writing a hook in my contentelement-extension this contents are in the index now. I thought i only have to put the own fields (they exist in the tt_content table) in the Field "Content element types which should be indexed (default: text,textpic,bullets,table,html,header,uploads)" in my indexer configuration, but that was not effective.

Now i have to index the contents in the field "subheader" too. Even if i put the subheader in the above mentioned field or if i set it in my own indexer, the subheader is not indexed.

Working with kesearch 3.1.5 and kesearchpremium 3.1.0

**Comment by christianbltr** [comment]
Unfortunately it is currently not that easy to index custom fields in tt_content. This question comes up from time to time so I added a documentation page about it:

https://github.com/teaminmedias-pluswerk/ke_search/blob/dd3ead81bfb5e32f542f21960311b78d64f9a52c/Documentation/Indexing/IndexerTypes/CustomContentFields.rst

For the future it may be a good idea to add a configuration field "fields to index" so that adding custom fields would much easier.
