### ISSUE TITLE
Disable Index for an entire section of the pagetree

### ISSUE THREAD

**Issue by Fistandantilus** [teaminmedias-pluswerk/ke_search#387]
Is there a possibility that the search index can be deactivated for an entire section of the pagetree?
This might be possible with an extended template such as tx_kesearch.disableIndex = 1.

**Comment by christianbltr** [comment]
I agree that this would be a useful feature. 
I think we should not go with typoscript template approach because we then would need to have a frontend instantiated.
I think the configuration should be stored in the indexer configuration. Much like the filter option setting "Exclude tag for all children of this page" allows to exclude pages recursively from automated tagging.

**Comment by christianbltr** [comment]
Moved to https://github.com/tpwd/ke_search/issues/103
