### ISSUE TITLE
tx_news searchresults are not cropped with highlighted word like normal pages searchresults

### ISSUE THREAD

**Issue by alsodenn** [teaminmedias-pluswerk/ke_search#396]
The teasers of the search results for normal pages look something like this:

```
... et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lore
      m ipsum dolor sit amet. <span class="hit">search word</span>&nbsp;Lorem ipsum do
      lor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor inv
```

How do I make tx_news search results look like this? So that it displays the correct text section with the search word in it as a teaser? Is that possible at all for tx_news content? Or why is that not standard? I find it strange that there are different teaser outputs here.

**Comment by christianbltr** [comment]
Most likely this is a result of the plugin configuration.

You can define wether the result list should show the teaser (abstract) of a result or an extract of the entire element with the search word highlighted.

Go to your search box plugin in the tab "General Layout" and set "Text for used for search result (preview text)" to "Show abstract if it contains searchword, otherwise show an excerpt from the content."

**Comment by alsodenn** [comment]
Great, that was exactly the solution! Many Thanks!
