### ISSUE TITLE
Order search results by filter

### ISSUE THREAD

**Issue by dbachmann** [teaminmedias-pluswerk/ke_search#41]
I did a small modification in ke_search and maybe my idea is interesting for the master-branch. 

I had to order the search results by filter types. First my own type, then news and at the end pages and files. I tried it first by fluid but I had no chance to set an order. So I added a sorting field in the indexer configuration to specify an order in the backend and added another sorting field in the index table to store the value from the indexer. 

Now I can set an order for the indexers in the backend and the results will appear in this order. With some fluid conditions it is also possible to give every entry group another styling now

[locallang_db.xml.txt](https://github.com/teaminmedias-pluswerk/ke_search/files/231920/locallang_db.xml.txt)
[tx_kesearch_index.php.txt](https://github.com/teaminmedias-pluswerk/ke_search/files/231921/tx_kesearch_index.php.txt)
[tx_kesearch_indexerconfig.php.txt](https://github.com/teaminmedias-pluswerk/ke_search/files/231922/tx_kesearch_indexerconfig.php.txt)
[ext_tables.sql.txt](https://github.com/teaminmedias-pluswerk/ke_search/files/231932/ext_tables.sql.txt)
[class.tx_kesearch_indexer.php.txt](https://github.com/teaminmedias-pluswerk/ke_search/files/231925/class.tx_kesearch_indexer.php.txt)

**Comment by seirerman** [comment]
I'm interested in this feature as well.

In certain cases I have 30 results, and the first 27 are downloads. The relevant pages are the last 3 search results. 

I know this is also a SEO issue on my side, but an option to rank pages higher than news articles or downloads would be great. Or any tips for ke_search SEO, while we are at it. ;-)

**Comment by dbachmann** [comment]
Well, I added this feature 3 years ago and attached the changes in my post. Just download the files above and add them in your extension directory.

**Comment by seirerman** [comment]
I know, and that's great!

My comment was more directed to integrating this feature in ke_search directly.

**Comment by dbachmann** [comment]
Ahh ok. 

I think we have to wait. Maybe someone will include this small change in the extension.

**Comment by christianbltr** [comment]
This can now be achieved using the "custom ranking" feature of ke_search_premium:
http://dev.kesearch.de/documentation/ke_search_premium/Features/CustomRanking.html

### Custom Ranking

The “custom ranking” feature allows you to give a numeric value to pages and indexer configurations. You can then configure ke_search to sort the result list using this custom value. If both (pages and indexer configuration) values are set, the will be summed up.

#### Use case examples

-    Show all page records before other records (eg. files or news).
-    Show product pages on top.
-    Show pages about persons on top.
-    Show certain results at the end of the list.

#### Notes

-    This feature does not work together with the “Sphinx”-feature.
-    This feature needs at least ke_search 3.1.5 because before that it was not possible to use multiple sortings.

#### Configuration

You can enable/disable the custom ranking feature in the settings module in the extension configuration in the tab “Ranking”.

After that please set the sorting to “Custom ranking DOWN” and “Relevance DOWN” in the plugin options (needs at least ke_search 3.1.5).

#### Usage

You will find a field “Custom ranking value” in the page properties in the tab “Search” and in indexer configurations.

By setting this value, the page or the records fetched by this indexer configuration will be sorted to the very top of the result list. If both values are set, they will be summed up. You can also set negative values to push results to the end of the list.
