### ISSUE TITLE
Use locallang for date formats

### ISSUE THREAD

**Issue by tpinne** [teaminmedias-pluswerk/ke_search#44]
Currently `$GLOBALS['TYPO3_CONF_VARS']['SYS']['ddmmyy']` is used to format the dates in the results list. This makes it impossible to use proper date formatting for different locales.

**Comment by christianbltr** [comment]
Yes, that should be fixed.
Since the new indexer for the "cal" extension has been implemented, the locallang values already exist, but the only the output of the calendar dates use them right now.

**Comment by christianbltr** [comment]
In the current version of ke_search the timestamp value `{resultrow.date_timestamp}` is avilable additonally to `{resultrow.date}` which is already formatted.

So the date can be formatted eg. by using

```
<f:format.date format="%d. %B %Y">{resultrow.date_timestamp}</f:format.date>
```

The default template uses now {resultrow.date_timestamp} instead of {resultrow.date} which should make it easier for integrators to see how to adjust the date formatting.

This is now also documented in "Templating" --> "Custom values in the search result list"
