### ISSUE TITLE
filter.shownumberofresults broken?

### ISSUE THREAD

**Issue by mkrappitz** [teaminmedias-pluswerk/ke_search#445]
To me it looks that the Filter setting "Soll die Anzahl der Treffer pro Filteroption angezeigt werden?" [shownumberofresults] is broken in latest EXT_ke_search 4.4.4. When activating it the numbers are not being displayed for example in the checkbox filtering in the frontend because in the fluid partial EXT:ke_search/Resources/Private/Partials/Filters/Checkbox.html the variable {option.results} is always 0. In EXT:ke_search 3.7.2 it was not 0.

**Comment by christianbltr** [comment]
I could not reproduce this issue. Showing the number of search results per filter option works in my test environment.

![Auswahl_051](https://user-images.githubusercontent.com/11410553/174266208-4507edf3-630a-4e8f-8911-f4161bebbfb0.png)

If you upgraded from ke_search 3.7.2 it may be that the templates have changed since then. Please check if the issue is still there with the default templates shipped with the current version of the extension.

Please use 
https://github.com/tpwd/ke_search/issues
for further issues.

**Comment by mkrappitz** [comment]
OK, sorry, I needed to be more specific on this one. Initially, all is good, numbers being shown:

![grafik](https://user-images.githubusercontent.com/5528239/174279143-a078bfa6-6e58-46db-b94c-86c4d9dacd3d.png)

Once the submit button "Finden" gets clicked with any number of checkboxes selected (even when having all checked, search term entered or not), all numbers disappear:

![grafik](https://user-images.githubusercontent.com/5528239/174279315-13d8536a-d55f-4643-8b32-906df3e79ece.png)

This is the URL after clicking the submit button:
https://www.domain.com/suche/?tx_kesearch_pi1%5Bfilter_1_1%5D=product&tx_kesearch_pi1%5Bfilter_1_2%5D=news&tx_kesearch_pi1%5Bfilter_1_3%5D=recipe&tx_kesearch_pi1%5Bfilter_1_4%5D=content&tx_kesearch_pi1%5Bfilter_1_5%5D=teataster&cHash=0b6199c43f981244a88120cd1f56dbfa

**Comment by mkrappitz** [comment]
Could you reopen?

**Comment by christianbltr** [comment]
I'm sorry, I'm still not able to reproduce this.

In my test this is initial state of the search form:

![Auswahl_052](https://user-images.githubusercontent.com/11410553/175487332-b54faa29-691b-4e39-a250-2f7a82784a88.png)

This is the state after activating all three checkboxes and clicking "Find":

![Auswahl_053](https://user-images.githubusercontent.com/11410553/175487427-1cb4348e-8350-49d6-a126-62329691f847.png)

The number of results is shown next to the filter.

**Comment by mkrappitz** [comment]
OK, strange. I also deactivated markAllCheckboxes in the filter settings like you. But it stays the same, when I check all checkboxes and submit the search form the numbers next to the filters disappear. We have EXT:ke_search 4.4.5 with unchanged templates, clean TYPO3 10.4.30 (with EXT:news, EXT:vhs, EXT:mask, EXT:min, EXT:form_to_database, EXT:ns_all_lightbox, EXT:secure_downloads, EXT:webp, and a custom coded extbase product catalogue and nothing else notworthy). If It's intereseting for you to look at, I can give system access or screen sharing.

**Comment by christianbltr** [comment]
For the records:

You need to set "Availability check for filter conditions" to "Check in condition with other filters" in the plugin options, tab "Filter", then the number of results per filter option will be showed after the search has been executed.

The disadvantage is, that you will need to reset the search in order to select other checkbox filter options.

![Auswahl_059](https://user-images.githubusercontent.com/11410553/176851584-2896e179-d22d-4245-a1ff-00c0b4942396.png)

**Comment by mkrappitz** [comment]
ok, understand. I think that is a bit strange behaviour, as the setting doesn't obviously imply that numbers will be gone if you don't set this to "multi", but OK. Thanks for the carification.
