### ISSUE TITLE
Provide RealURL suggested configuration

### ISSUE THREAD

**Issue by gaumondp** [teaminmedias-pluswerk/ke_search#71]
I've looked in the documentation and Google in general and didn't find a common/suggested RealURL configuration to make search paths more meaningful.

Something like this (simple & advanced) would be helpful: https://docs.typo3.org/typo3cms/extensions/news/AdministratorManual/BestPractice/Realurl/Index.html

Thanks!

**Comment by hilburger** [comment]
Hey guys, actually a very nice extension but the lack of any example configuration is preventing us to use this for client who are also willing to pay for the pro version. 
But no one will buy it without the basic version running. :-(

**Comment by christianbltr** [comment]
Since version 3.4.0 ke_search supports routing / speaking URLs for TYPO3 9 and above. An example can be found in the documentation https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/3.4/en-us/Configuration/RoutingSpeakingUrls.html

There won't be an example for RealURL though, so I'm closing this.
