### ISSUE TITLE
Error while starting the indexer: [] operator not supported for strings (PHP 7.1)

### ISSUE THREAD

**Issue by derandy** [teaminmedias-pluswerk/ke_search#86]
Starting the indexer in the Backend throws an Error which is related to PHP 7.1 afaik
Neither the BackendModule nor the scheduler is working.

```
[] operator not supported for strings

Error thrown in file
/../../typo3conf/ext/ke_search/Classes/hooks/class.user_kesearchhooks.php in line 41.
```

**Comment by steffenk** [comment]
this can be fixed easy:

tx_kesearch_indexer, line 40:
change `var $additionalFields = '';` into `var $additionalFields = [];`

**Comment by a-r-m-i-n** [comment]
I am not able to reconstruct this issue. Tested with PHP 7.1.5 (7.1.5-1+deb.sury.org~xenial+1).

Also the `\user_kesearch_sortdate::registerAdditionalFields` method expects an array as parameter (which is referenced). So instead of overwriting the array always with an empty one, we should ensure that just arrays are passed to the method. We could also type hint the expected array, to make this method more strict.

As far as I can see in tx_kesearch_indexer, the default value for `$this->additionalFields` is already an array. So the only reason I can imagine why you got this issue, is that another registred hook destroys the array...

**Comment by christianbltr** [comment]
In class.tx_kesearch_indexer.php in Line 38 $additionalFields is already defined as $array.
It has been fixed in 
https://github.com/teaminmedias-pluswerk/ke_search/commit/4d7439a50fa0a3c1cc56964c64bc3a5ca1dec93b
So I'm closing this.
